### PR TITLE
Add notebook example for doing simultaneous calcs

### PR DESCRIPTION
**Pull request by psavery**
This gives examples for:

1. Running simultaneous calculations in the same docker container.
2. Creating molecules that do not have 3D coordinates.

It also provides some extra examples such as what happens when
a 3D calculation is attempted on a 2D molecule.

Signed-off-by: Patrick Avery <patrick.avery@kitware.com>

### CODE REVIEW

**Comment by psavery** [comment]
Along with [this PR](https://github.com/OpenChemistry/openchemistrypy/pull/85), this notebook seems to work fine for me, except that I have to use my locally built chemml docker image instead of the one on openchemistry. Maybe we need to update the one on openchemistry?

**Comment by cjh1** [comment]
@psavery The chemml one should be rebuilt now, can you confirm that this now works?

**Comment by cjh1** [comment]
This is looking good, 'simultaneous' is probably not the best name. They are being run in serialize. May be just 'MultipleCalculations'.

**Comment by psavery** [comment]
I renamed it. I'll try re-running it with the latest chemml.

**Comment by psavery** [comment]
Yep! I ran through the whole notebook, and it seemed to work fine now! I think this branch is ready!

**Pull request merged**
