### PR TITLE
Autodetect bonds on calculation ingestion

### PR DESCRIPTION
**Pull request by alesgenova**

### CODE REVIEW

**Comment by psavery** [comment]
It's not urgent, but maybe in the future, we can simplify the process by exposing [Avogadro's bond perception](https://github.com/OpenChemistry/avogadrolibs/blob/master/avogadro/core/molecule.h#L533) to the python API, or add a bond perception option to the cjson reader like [the one for xyz](https://github.com/OpenChemistry/avogadrolibs/blob/master/avogadro/io/xyzformat.cpp#L154).

**Comment by cryos** [comment]
I think we can add bond perception as an option, but it will only get single bonds based on a simple distance metric.

**Comment by cryos** [comment]
@alesgenova @cjh1 does this need merging/deploying to get PSI4 bonding working?

**Comment by cjh1** [comment]
@cryos I will deploy when a new image is built

**Pull request merged**
