### PR TITLE
Allow molecules to be searched with min/max values

### PR DESCRIPTION
**Pull request by psavery**
In the minValues parameter, one can pass in things like:
```
{ "properties.heavyAtomCount": 4 }
```

and the results will only contain molecules that have at
least 4 heavy atoms. The maxValues parameter can be used
in a similar way.

If both the minValues and maxValues parameters are used, then
the results will satisfy both.

Signed-off-by: Patrick Avery <patrick.avery@kitware.com>

### CODE REVIEW

**Comment by psavery** [comment]
This works toward some of the content of [this issue](https://github.com/OpenChemistry/42/issues/11).

**Comment by psavery** [comment]
This is ready for review.

**Comment by psavery** [comment]
As a side note, this also provides an indirect way to search for exact values as well, because the user can specify something like `{ "properties.heavyAtomCount": 4 }` as both a min value and a max value (in which case it must be equal).

**Comment by cryos** [comment]
Wouldn't it be more efficient to add an endpoint to search for an exact match? I don't know how clever MongoDB is about optimizing that, but it seems a little strange not to simply offer an equality query too.

**Comment by psavery** [comment]
Yes, that makes sense. I can add it.

**Comment by psavery** [comment]
Well, I actually just noticed that everything I added in this PR and more (equality comparisons included) are already available to use in the `GET /molecules/search` endpoint with the `query` parameter. It looks like Chris added these features several years ago ([implementation here](https://github.com/OpenChemistry/mongochemserver/blob/master/girder/molecules/molecules/query.py)). I'm not sure why we haven't been using it - I can ask Chris about it when he gets back.

**Comment by cryos** [comment]
I thought you knew about that, I think it may need updating to our new document layout. We used it to great effect in a previous project, but it was kept around for reference. It would be nice to update it, and get it working again.

**Comment by psavery** [comment]
Seems like, for the most part, it is working and in good condition. It worked for me for inchi, inchikey, name, formula, smiles, mass, atomCount, and heavyAtomCount. I also tried the `gte`, `lte`, `gt`, `lt`, `eq`, and `ne` operators, and various combinations of them with `and` and `or`.

The only thing that didn't work for me so far is more complex InChIs. For instance, the InChI that we get from Open Babel for butanol is `InChI=1S/4CH4.H2O/h4*1H4;1H2`. It raises an invalid query exception, which might be because of a parsing error.

**Pull request merged**
