### PR TITLE
Improve Molecule Search Capabilities

### PR DESCRIPTION
**Pull request by psavery**
Added limit and offset parameters that the user can
set to limit the number of results. The default limit
is 25, and the default offset is 0.

Additionally, the results are returned with the limit
and offset information like so:
```
{
  "limit": 25,
  "matches": 3,
  "offset": 0,
  "results": [...]
}
```

Looks like this in the girder web interface:
Screenshot from 2019-05-13 11-57-14

I'm planning to add more changes to this PR (some of the changes mentioned [here](https://github.com/OpenChemistry/42/issues/11)).

### CODE REVIEW

**Comment by psavery** [comment]
@cryos @cjh1 I think this is ready for review. It adds pagination (limit, offset, and sort) to both `GET /molecules` and `GET /molecules/search`. The default is to limit to 25 results, and to sort by time of creation (with most recent first).

Screenshot from 2019-05-13 14-56-00

I don't think any more changes need to be made to mongochemdeploy and openchemistrypy (other than [this PR](https://github.com/OpenChemistry/openchemistrypy/pull/78). There may need to be a few small changes to mongochemclient, but perhaps @alesgenova can help with that.

Should I go ahead and add pagination to calculations in this PR as well, or do calculations in a separate PR?

**Comment by psavery** [comment]
Actually, I just found at least one more thing I need to change in openchemistrypy...

**Comment by cjh1** [comment]
@psavery Can you run a test with a large number of molecules, say 1000000 ( they can all be the same ) and try todo a get with a large offset, my concern is that there will be a high cost of skip through the cursor.

**Comment by psavery** [comment]
FYI: I currently have around 37K methane molecules. If I try to get them all (no limit), there is an error with the sorter. I guess it can only sort so many molecules.
```
OperationFailure: OperationFailure('Executor error during find command: OperationFailed: Sort operation used more than the maximum 33554432 bytes of RAM. Add an index, or specify a smaller limit.')
```

**Comment by psavery** [comment]
I have ~180K methane molecules now. So far, if I run it without any sorting, it is pretty fast. But if I try to offset around 40K or greater and run the sort, I get the above error message:
```
OperationFailure: OperationFailure('Executor error during find command: OperationFailed: Sort operation used more than the maximum 33554432 bytes of RAM. Add an index, or specify a smaller limit.')
```

I wonder if this means we will need to find a different way to do the sorting.

**Comment by cryos** [comment]
Did you try adding an index on the field being sorted?

**Comment by cjh1** [comment]
@cryos beat me to it!

**Comment by psavery** [comment]
@cryos @cjh1 That fixed the issue! I guess we just need to make sure that an index exists for each field we want to be able to sort by.

**Comment by psavery** [comment]
@cryos I got rid of the `created` tag and we are now just sorting by `_id`, which seems to work fine for sorting by most recently created.

I'm at around ~262K methane molecules in the database. Sorting by `_id` with a large offset so far seems to work relatively quickly and fine.

**Comment by cryos** [comment]
I wasn't really against having a created and possibly a modified key as they are useful entities on their own. I would count them as useful metadata to display though, and reuse _id as it already has an index on it for sorting by creation (it that works reliably, and we can sort by most recently added being first).

**Comment by psavery** [comment]
Well, one nice thing I found about the `ObjectId` is that you can actually extract the time of creation from it using [generation_time](http://api.mongodb.com/python/current/api/bson/objectid.html#bson.objectid.ObjectId.generation_time). For instance, for one of my molecules, `mol['_id'].generation_time` returns `2019-05-17T17:35:31+00:00`. So I was thinking we could use that instead of a `created` key. But we could certainly add a `modified` key!

**Comment by cryos** [comment]
That is great, I wondered if it was possible to do that.

**Comment by psavery** [comment]
@cryos @cjh1 I think we need to add a `creator` key so we can search for all molecules created by a user. Does that sound good? I currently do not see another way to figure out who created a molecule (you can see who has admin privileges over the molecule, but that could potentially be multiple people).

**Comment by cjh1** [comment]
@psavery Sounds good. But `creatorId` should be an `ObjectId` rather than a string.

**Comment by psavery** [comment]
@cjh1 Okay. That means we'll need to create and ObjectId [here](https://github.com/OpenChemistry/mongochemserver/pull/124/files#diff-68b829f09eca1232b76a2e23392c1eb1R42) when doing a query. But I can do that.

**Pull request merged**
